### ISSUE TITLE
Exact collision detection

### ISSUE THREAD

**Issue by hwilms** [namsk/spritekit-swift-physics-bouncing-balls#1]
Hi,

I am experiencing collisions that are not exact in your demo. Sometimes a ball collides to early, i.e. above the other ball and sometime too late, i.e. the ball actually drops into the other ball and then bounces back. I know that there have been issues with the SK physics engine and I was wondering if, there are any solutions, especially with iOS 8.1?

Best regards,
Hartmut

**Comment by namsk** [comment]
Hi,

First, I apologize the I am not fluent in English.
I do not test my demo with iOS 8.1, so I don't know if my demo works well
or not.
1. Do you mean my demo does not works well with iOS 8?
2. Actually, I don't exactly understand physics body in SpriteKit. Are you
   sure that you set the collision area correctly? Please check it out.

I never know someone is interested in my demo project, I really need to
thank you.
I hope you to find good solution, and I think you can do.

SIncerely,
SeungKyun Nam

2014-10-23 15:35 GMT+09:00 hwilms notifications@github.com:
