### ISSUE TITLE
Changes needed for XCode 6.3.1.

### ISSUE THREAD

**Issue by stephmur** [namsk/spritekit-swift-physics-bouncing-balls#2]
Due to changes in Swift syntax, the following changes are needed to make the project compile. I'm not an expert in Swift but these changes seem to work:
1. In the file AppDelegate.swift, Class AppDelegate the "application" declaration needs to change:
   // Old:
   //func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: //NSDictionary?) -> Bool { 
   // New:
   func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
2. In GameScene.swift the following needs to change:
   // Old:
   // override func touchesBegan(touches: NSSet, withEvent event: UIEvent) {
   // New:
   override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
3. In GameViewController.swift change:
   // Old:
   //      let skView = self.view as SKView
   // New: 
       let skView = self.view as! SKView

Sorry if this is not the correct way to submit changes, but I'm new at this. I just thought this might be helpful for other newcomers to Swift like me.

  --Steve

**Comment by namsk** [comment]
Thanks, I'll check :)

**Comment by namsk** [comment]
Fixed.

Thanks.
